name: PyTorch
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - absl-py=1.3.0=py37haa95532_0
  - aiohttp=3.8.3=py37h2bbff1b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - async-timeout=4.0.2=py37haa95532_0
  - asynctest=0.13.0=py_0
  - attrs=22.1.0=py37haa95532_0
  - blas=1.0=mkl
  - blinker=1.4=py37haa95532_0
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - ca-certificates=2024.9.24=haa95532_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2022.12.7=py37haa95532_0
  - cffi=1.15.1=py37h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py37haa95532_0
  - colorama=0.4.6=py37haa95532_0
  - cryptography=39.0.1=py37h21b164f_0
  - cuda-cccl=12.6.77=0
  - cuda-cccl_win-64=12.6.77=0
  - cuda-cudart=11.7.99=0
  - cuda-cudart-dev=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-libraries-dev=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvrtc-dev=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-opencl=12.6.77=0
  - cuda-opencl-dev=12.6.77=0
  - cuda-profiler-api=12.6.77=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.6=3
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.3.3=py37h2bbff1b_0
  - future=0.18.3=py37haa95532_0
  - giflib=5.2.2=h7edc060_0
  - google-auth=2.6.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - grpcio=1.42.0=py37hc60d5dd_0
  - idna=3.4=py37haa95532_0
  - importlib-metadata=4.11.3=py37haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - jpeg=9e=h827c3e9_3
  - lerc=3.0=hd77b12b_0
  - libcublas=11.10.3.66=0
  - libcublas-dev=11.10.3.66=0
  - libcufft=10.7.2.124=0
  - libcufft-dev=10.7.2.124=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.7.77=0
  - libcusolver=11.4.0.1=0
  - libcusolver-dev=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libcusparse-dev=11.7.4.91=0
  - libdeflate=1.17=h2bbff1b_1
  - libnpp=11.7.4.75=0
  - libnpp-dev=11.7.4.75=0
  - libnvfatbin=12.6.77=0
  - libnvfatbin-dev=12.6.77=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=11.8.0.2=0
  - libnvjpeg-dev=11.8.0.2=0
  - libpng=1.6.39=h8cc25b3_0
  - libprotobuf=3.20.3=h23ce68f_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown=3.4.1=py37haa95532_0
  - markupsafe=2.1.1=py37h2bbff1b_0
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - multidict=6.0.2=py37h2bbff1b_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - numpy=1.21.5=py37h7a0a035_3
  - numpy-base=1.21.5=py37hca35cd5_3
  - oauthlib=3.2.1=py37haa95532_0
  - openssl=1.1.1w=h2bbff1b_0
  - pillow=9.4.0=py37hd77b12b_0
  - pip=22.3.1=py37haa95532_0
  - protobuf=3.20.3=py37hd77b12b_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.4.0=py37haa95532_0
  - pyopenssl=23.0.0=py37haa95532_0
  - pysocks=1.7.1=py37_1
  - python=3.7.2=h8c8aaf0_10
  - pytorch=1.13.1=py3.7_cuda11.7_cudnn8_0
  - pytorch-cuda=11.7=h16d0643_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0=py37h2bbff1b_1
  - requests=2.28.1=py37haa95532_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - setuptools=65.6.3=py37haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - tensorboard=2.10.0=py37haa95532_0
  - tensorboard-data-server=0.6.1=py37haa95532_0
  - tensorboard-plugin-wit=1.8.1=py37haa95532_0
  - tk=8.6.14=h0416ee5_0
  - tqdm=4.64.1=py37haa95532_0
  - typing-extensions=4.4.0=py37haa95532_0
  - typing_extensions=4.4.0=py37haa95532_0
  - urllib3=1.26.14=py37haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vs2015_runtime=14.40.33807=h98bb1dd_1
  - werkzeug=2.2.2=py37haa95532_0
  - wheel=0.38.4=py37haa95532_0
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yarl=1.8.1=py37h2bbff1b_0
  - zipp=3.11.0=py37haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - torchaudio==0.13.1
      - torchvision==0.14.1
